# Generated by Django 5.1.3 on 2024-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_food', models.CharField(max_length=100)),
                ('preferred_cuisine', models.CharField(max_length=100)),
                ('dietary_restrictions', models.CharField(max_length=100)),
            ],
        ),
    ]
